permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"
highlighter: rouge
categories: [project, post]
excerpt_separator: <!--more-->

exclude:
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
