highlighter: pygments
categories: [project, post]
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "base"
      author: "GISCIA"
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "base"
exclude:
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
